title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

project:
  type: website
  output-dir: docs

bibliography: referencias.bib
csl: apa.csl

website:
  title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Inicio

      - section: "Clase 0"
        contents:
          - href: clase0/index.qmd
            text: Presentación
          - href: clase0/teoria.qmd
            text: "Teoría 0"
          - href: clase0/practica-guiada.qmd
            text: "Práctica guiada 0"
          - href: clase0/practica-estudiantes.qmd
            text: "Práctica para estudiantes 0"

      - section: "Clase 1"
        contents:
          - href: clase1/index.qmd
            text: Presentación
          - href: clase1/teoria.qmd
            text: "Teoría"
          - href: clase1/practica-guiada.qmd
            text: "Práctica guiada 1"
          - href: clase1/practica-estudiantes.qmd
            text: "Práctica para estudiantes 1"
            
      - section: "Clase 2"
        contents:
          - href: clase2/index.qmd
            text: Presentación
          - href: clase2/teoria.qmd
            text: "Teoría 2"
          - href: clase2/practica-guiada.qmd
            text: "Práctica guiada 2"
          - href: clase2/practica-estudiantes.qmd
            text: "Práctica para estudiantes 2"


      - section: "Clase 3"
        contents:
          - href: clase3/index.qmd
            text: Presentación
          - href: clase3/teoria.qmd
            text: "Teoría 3"
          - href: clase3/practica-guiada.qmd
            text: "Práctica guiada 3"
          - href: clase3/practica-estudiantes.qmd
            text: "Práctica para estudiantes 3"

      - section: "Clase 4"
        contents:
          - href: clase4/index.qmd
            text: Presentación
          - href: clase4/teoria.qmd
            text: "Teoría 4"
          - href: clase4/practica-guiada.qmd
            text: "Práctica guiada 4"
          - href: clase4/practica-estudiantes.qmd
            text: "Práctica para estudiantes 4"
            
      - section: "Clase 5"
        contents:
          - href: clase5/index.qmd
            text: Presentación
          - href: clase5/teoria.qmd
            text: "Teoría 5"
          - href: clase5/practica-guiada.qmd
            text: "Práctica guiada 5"
          - href: clase5/practica-estudiantes.qmd
            text: "Práctica para estudiantes 5"
                        
      - section: "Clase 6"
        contents:
          - href: clase6/index.qmd
            text: Presentación
          - href: clase6/teoria.qmd
            text: "Teoría 6"
          - href: clase6/practica-guiada.qmd
            text: "Práctica guiada 6"
          - href: clase6/practica-estudiantes.qmd
            text: "Práctica para estudiantes 6"
format:
  html:
    theme: cosmo
    css: estilos.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true  
    
editor: visual