title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

project:
  type: website
  output-dir: docs

bibliography: referencias.bib
csl: apa.csl

website:
  title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Inicio

      - section: "Parte 1"
        contents:
          - href: parte1/index1.qmd
            text: Presentación
          - href: parte1/teoria1.qmd
            text: "Teoría"
          - href: parte1/practica-guiada1.qmd
            text: "Práctica guiada"
          - href: parte1/practica-estudiantes1.qmd
            text: "Práctica para estudiantes"
            
      - section: "Parte 2"
        contents:
          - href: parte2/index2.qmd
            text: Presentación
          - href: parte2/teoria2.qmd
            text: "Teoría"
          - href: parte2/practica-guiada2.qmd
            text: "Práctica guiada"
          - href: parte2/practica-estudiantes2.qmd
            text: "Práctica para estudiantes"


      - section: "Parte 3"
        contents:
          - href: parte3/index3.qmd
            text: Presentación
          - href: parte3/teoria3.qmd
            text: "Teoría"
          - href: parte3/practica-guiada3.qmd
            text: "Práctica guiada"
          - href: parte3/practica-estudiantes3.qmd
            text: "Práctica para estudiantes"

      - section: "Parte 4"
        contents:
          - href: parte4/index4.qmd
            text: Presentación
          - href: parte4/teoria4.qmd
            text: "Teoría"
          - href: parte4/practica-guiada4.qmd
            text: "Práctica guiada"
          - href: parte4/practica-estudiantes4.qmd
            text: "Práctica para estudiantes"
            
      - section: "Parte 5"
        contents:
          - href: parte5/index5.qmd
            text: Presentación
          - href: parte5/teoria5.qmd
            text: "Teoría"
          - href: parte5/practica-guiada5.qmd
            text: "Práctica guiada"
          - href: parte5/practica-estudiantes5.qmd
            text: "Práctica para estudiantes"
                        
      - section: "Parte 6"
        contents:
          - href: parte6/index6.qmd
            text: Presentación
          - href: parte6/teoria6.qmd
            text: "Teoría"
          - href: parte6/practica-guiada6.qmd
            text: "Práctica guiada"
          - href: parte6/practica-estudiantes6.qmd
            text: "Práctica para estudiantes"
format:
  html:
    theme: cosmo
    css: estilos.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true  
    
editor: visual