title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

project:
  type: website
  output-dir: docs

bibliography: referencias.bib
csl: apa.csl

website:
  title: "Análisis y modelado de datos para investigaciones en biociencias con R y RStudio"

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Inicio

      - section: "Clase 0"
        contents:
          - href: clase0/index.qmd
            text: Presentación
          - href: clase0/teoria0.qmd
            text: "Teoría"
          - href: clase0/practica-guiada0.qmd
            text: "Práctica guiada"
          - href: clase0/practica-estudiantes0.qmd
            text: "Práctica para estudiantes"

      - section: "Clase 1"
        contents:
          - href: clase1/index1.qmd
            text: Presentación
          - href: clase1/teoria1.qmd
            text: "Teoría"
          - href: clase1/practica-guiada1.qmd
            text: "Práctica guiada"
          - href: clase1/practica-estudiantes1.qmd
            text: "Práctica para estudiantes"
            
      - section: "Clase 2"
        contents:
          - href: clase2/index2.qmd
            text: Presentación
          - href: clase2/teoria2.qmd
            text: "Teoría"
          - href: clase2/practica-guiada2.qmd
            text: "Práctica guiada"
          - href: clase2/practica-estudiantes2.qmd
            text: "Práctica para estudiantes"


      - section: "Clase 3"
        contents:
          - href: clase3/index3.qmd
            text: Presentación
          - href: clase3/teoria3.qmd
            text: "Teoría"
          - href: clase3/practica-guiada3.qmd
            text: "Práctica guiada"
          - href: clase3/practica-estudiantes3.qmd
            text: "Práctica para estudiantes"

      - section: "Clase 4"
        contents:
          - href: clase4/index4.qmd
            text: Presentación
          - href: clase4/teoria4.qmd
            text: "Teoría"
          - href: clase4/practica-guiada4.qmd
            text: "Práctica guiada"
          - href: clase4/practica-estudiantes4.qmd
            text: "Práctica para estudiantes"
            
      - section: "Clase 5"
        contents:
          - href: clase5/index5.qmd
            text: Presentación
          - href: clase5/teoria5.qmd
            text: "Teoría"
          - href: clase5/practica-guiada5.qmd
            text: "Práctica guiada"
          - href: clase5/practica-estudiantes5.qmd
            text: "Práctica para estudiantes"
                        
      - section: "Clase 6"
        contents:
          - href: clase6/index6.qmd
            text: Presentación
          - href: clase6/teoria6.qmd
            text: "Teoría"
          - href: clase6/practica-guiada6.qmd
            text: "Práctica guiada"
          - href: clase6/practica-estudiantes6.qmd
            text: "Práctica para estudiantes"
format:
  html:
    theme: cosmo
    css: estilos.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true  
    
editor: visual