---
title: "Práctica Guiada 2"
editor: 
  markdown: 
    wrap: 72
---

## Preparación del entorno e importación

Los paquetes se instalan una única vez en la computadora. En cambio,
deben cargarse cada vez que se inicia una nueva sesión de trabajo en R.

``` r
install.packages("tidyverse")
install.packages("janitor")
```

1.  **Importar datos significa leer un archivo externo y convertirlo en
    un objeto que R pueda utilizar.**

``` r
agro <- read_csv("../datos originales/Agrofood_co2_emission.csv")
```

A partir de este momento, agro será nuestro objeto de trabajo.
Modificarlo no cambia automáticamente el archivo CSV original.

Según la extensión del archivo a importar hay diferentes caminos

  Cuando los datsso están separados por ;
```r
datos <- read_csv2("../datos originales/archivo.csv")
```

Esta función interpreta, por defecto, el punto y coma como separador de
columnas y la coma como separador decimal.


* Archivos de Excel

Para importar archivos de Excel con extensión `.xlsx` o `.xls` se utiliza
el paquete `readxl`. Si aún no está instalado, debe instalarse una sola vez:

```r
install.packages("readxl")
```

En cada sesión en la que se lo necesite, se carga el paquete:

```r
library(readxl)
```

Luego se importa el archivo:

```r
datos <- read_excel("../datos originales/archivo.xlsx")
```

Si el libro contiene varias hojas, puede indicarse cuál se desea leer:

``` r
datos <- read_excel(
  "../datos originales/archivo.xlsx",
  sheet = "Hoja1"
)
```
* Archivos de texto

Cuando los datos se encuentran en un archivo de texto, se puede utilizar
`read_delim()`. Debe indicarse cuál es el separador entre las columnas.

* Para datos separados por tabulaciones:

```r
datos <- read_delim(
  "../datos originales/archivo.txt",
  delim = "\t"
)
```

Para datos separados por otro símbolo, por ejemplo una barra vertical:

```r
datos <- read_delim(
  "../datos originales/archivo.txt",
  delim = "|"
)
```

2.  **Reconocimiento de la estructura de la base**

En esta base, cada fila representa información de un área o país en un
año determinado. Las columnas representan variables, por ejemplo, las
emisiones por distintos rubros, la población y la temperatura media.

``` r
dim(agro)

nrow(agro)

ncol(agro)
```

``` r
glimpse(agro)
```

La función `glimpse()` permite observar los nombres de las variables,
sus tipos y algunos de sus valores.

3.  **Limpieza de nombres**

Los nombres originales contienen espacios, mayúsculas, paréntesis y
símbolos. Para trabajar de manera más sencilla, los normalizaremos.

``` r
agro <- agro |>
  clean_names()

names(agro)
```

Por ejemplo:

Area → area\
Year → year\
Average Temperature °C → average_temperature_c

Total Population - Female → total_population_female

A partir de este punto se utilizarán los nombres limpios.

4.  **Tipos de variables**

En la base predominan variables de texto y variables numéricas.

area contiene nombres de países o regiones. year representa el año de
cada registro. Las emisiones, la población y la temperatura son
variables numéricas.

``` r
class(agro$area)

class(agro$year)

class(agro$total_emission)
```

Aunque year está expresada mediante números, representa el tiempo y se
mantendrá como variable numérica para estudiar posteriormente su
evolución.

5.  **Selección y reordenamiento de variables**

Seleccionar variables significa conservar determinadas columnas de la
base. Esta operación no elimina filas.

a.  seleccionar algunas variables especificas: area, year,
    total_emission, average_temperature_c

``` r
agro |>
  select(area, year, total_emission, average_temperature_c)
```

b.  Seleccionar las varaialbes desde áreas hasta rice_cultivation

``` r
agro |>
  select(area:rice_cultivation)
```

Selccionar las variables que tienen una determinada parlabra. Ejemplo,
"population" Observación: la palabar debe ir entre comillas

``` r
agro |>
  select(area, year, contains("population"))
```

Seleccionar las variables que terminan en una deteminada palabra, por
ejemplo "fires"

``` r
agro |>
  select(ends_with("fires"))
```

c.  Eliminar una variable se utliza la función `select()` y se escribe
    la varaible precedida por el signo -

```         
agro |>
  select(-average_temperature_c)
```

Podemos crear una base reducida para trabajar con algunas variables
seleccionadas.

``` r
agro_reducida <- agro |>
  select(
    area,
    year,
    rural_population,
    urban_population,
    total_population_male,
    total_population_female,
    total_emission,
    average_temperature_c
  ) |>
  relocate(total_emission, .after = year)
```

`relocate(total_emission, .after = year)` sirve para ordenar un
variable. Se puede adicionar

.after =...-\> después de...

.besfore=... -\> antes de...

6.  Filtrado y ordenamiento de observaciones

Mientras select() trabaja con columnas, filter() permite conservar las
filas que cumplen una condición.

``` r
agro |>
  filter(area == "Argentina")
```

``` r
agro |>
  filter(year == 2020)
```

``` r
agro |>
  filter(
    area == "Argentina",
    year == 2020
  )
```

``` r
agro |>
  filter(
    area %in% c(
      "Argentina",
      "Bolivia (Plurinational State of)",
      "Brazil",
      "Chile",
      "Paraguay",
      "Uruguay"
    )
  )
```

``` r
agro |>
  arrange(total_emission)
```

``` r
agro |>
  arrange(area, year)
```

7.  **Creación y recodificación de variables**

La función mutate() permite crear nuevas variables o modificar las
existentes.

``` r
agro <- agro |>
  mutate(
    total_population =
      total_population_male + total_population_female,
    
    urban_population_percentage =
      100 * urban_population / total_population,
    
    positive_temperature_change =
      average_temperature_c > 0
  )
```

También podemos crear una variable para distinguir a Argentina de otros
paises

``` r
agro <- agro |>
  mutate(
    grupo_region = case_when(
      area == "Argentina" ~ "Argentina",
      
      TRUE ~ "Otros países o regiones"
    )
  )
```

8.  **Valores faltantes y duplicados**

Un valor faltante se representa en R mediante NA. No significa que el
valor sea cero, sino que la información no está disponible.

``` r
sum(is.na(agro))
```

``` r
agro |>
  summarise(
    across(
      everything(),
      ~ sum(is.na(.x))
    )
  )
```

Para detectar si existen filas completamente duplicadas:

``` r
sum(duplicated(agro))
```

``` r
agro |>
  count(area, year) |>
  filter(n > 1)
```

En esta base, debería haber como máximo una observación por combinación
de área y año.

Antes de eliminar duplicados, es necesario investigar por qué aparecen.

9.  **Resúmenes agrupados iniciales**

La combinación de group_by() y summarise() permite organizar y resumir
información para distintos grupos.

``` r
agro |>
  group_by(area) |>
  summarise(
    cantidad_anios = n(),
    primer_anio = min(year),
    ultimo_anio = max(year)
  )
```

En las próximas clases utilizaremos estas mismas funciones para calcular
medidas descriptivas y comparar las emisiones entre países y rubros.

10. Construcción y guardado de la base limpia

Finalmente, construiremos una versión ordenada de la basecon los países
de América del Sur incluidos, que utilizaremos en las clases siguientes.

``` r
agro_sudamerica <- agro |>
  filter(
    area %in% c(
      "Argentina",
      "Bolivia (Plurinational State of)",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela (Bolivarian Republic of)"
    )
  )
```

Creamos una nueva variable de clasifiación para idenitificar Argentina,
los paises límitrofes y los restantes

``` r
agro_sudamerica <-agro_sudamerica  |>
  mutate(
    grupo_region = case_when(
      area == "Argentina" ~ "Argentina",
      
      area %in% c(
        "Bolivia (Plurinational State of)",
        "Brazil",
        "Chile",
        "Paraguay",
        "Uruguay"
      ) ~ "Países limítrofes",
      
      TRUE ~ "Otros países de América del Sur"
    )
  ) |>
  arrange(area, year)
```

``` r
write_csv(
  agro_sudamerica,
  "../datos transformados/agro_sudamerica.csv"
)
```

También es posible guardarla como objeto de R. Este formato conserva
mejor las clases de las variables.

``` r
saveRDS(
  agro_sudamerica,
  "../datos transformados/agro_sudamerica.rds"
)
```

```         
agro_sudamerica2<- readRDS(
  "../datos transformados/agro_sudamerica.rds"
)
```

Al finalizar esta etapa, contaremos con una base limpia, ordenada y
preparada para realizar tablas, gráficos y análisis descriptivos.agro
\|\> select(-average_temperature_c)

Podemos crear una base reducida para trabajar con algunas variables
seleccionadas.

## Resumen de las  principlaes funciones utilizadas 

| Sección | Objetivos abordados | Funciones principales |
|:-----------------------|:-----------------------|:-----------------------|
| Preparación e importación | Importar un archivo CSV | `read_csv()` |
| Reconocimiento de la base | Reconocer filas, columnas, variables y observaciones | `dim()`, `nrow()`, `ncol()`, `names()`, `glimpse()`, `str()` |
| Limpieza de nombres | Trabajar con nombres consistentes | `clean_names()` |
| Selección y reordenamiento | Seleccionar y ordenar variables | `select()`, `relocate()` |
| Filtrado y ordenamiento | Filtrar y ordenar observaciones | `filter()`, `arrange()`, `between()`, `%in%` |
| Creación y recodificación | Crear y recodificar variables | `mutate()`, `case_when()` |
| Control de calidad | Detectar faltantes y duplicados | `is.na()`, `drop_na()`, `duplicated()`, `distinct()` |
| Resúmenes agrupados | Explorar subconjuntos de datos | `group_by()`, `summarise()`, `n_distinct()` |
| Base limpia | Guardar una nueva base de datos | `write_csv()`, `saveRDS()` |

## 
